### ISSUE TITLE
Static Build of iup ?

### ISSUE THREAD

**Issue by foxoman** [dariolah/niup#10]
Hi,

I really liked the update you made to the iup nim module,

It is the only sane gui available as i can see now with complete controls and multiplatform 

I just have a request if any way to build it and link it statically to the app instead of shipping the original iup.dll

**Comment by dariolah** [comment]
Out of box, no. With some modifications probably yes, haven't tried it

1. disable dynamic loading of libraries
--dynlibOverride:iup --dynlibOverride:iupcd --dynlibOverride:iupcontrols etc. for other libs (see niup.nimble)
OR
--dynlibOverrideAll in case you are only linking with IUP, no other libraries

2. tell linker to statically link IUP libraries
--passL:"-static -liup -liupcd etc. ..."

For windows I needed extra dynamic libraries for testing, could be that they are needed when deploying also.
libgcc_s_seh-1.dll, libstdc++-6.dll, libwinpthread-1.dll, boehmgc64.dll

It should be possible, even easy, but you will have to figure it out

**Comment by foxoman** [comment]
Yes I will be linking only with iup as all other libs are static ready for linux using alpine and for windows using msys.

Thank you very much I will be trying to figure out using your lead.
