### ISSUE TITLE
static build of iup (success) on windows and broken links

### ISSUE THREAD

**Issue by aldoniel** [dariolah/niup#11]
Hi,
Thanks a lot for writing this lib which seems to be the only mature, reasonably light and documented.

Using https://github.com/nim-lang/iup/issues/5 I managed to statically compile your example (on windows ; IUP 3.30 ; mingw64) with

`nim c -d:release --opt:speed --dynlibOverrideAll --passL:-mwindows -L:lib/libiup.a -L:lib/libiupcd.a -L:lib/libiupim.a -L:lib/libiupimglib.a -L:-lgdi32 -L:-luser32 -L:-lcomdlg32 -L:-lcomctl32 -L:-lole32 -L:-luuid test.nim`

where test.nim is your example, and /lib contains prebuild libraries for mingw64 static. The resulting exe runs fine (stand-alone in a sandbox, and weights 1.68Mb. 

For convenience, I also copied the dll (prebuild mingw64 dynamic) in the same directory as the debug exe for development in VS code.

You could maybe explain this (installation and compiler option) ? it seems interesting for some people, and this setup is complicated for newbies.

--
By the way, two broken links in "Installation"

Download tips:  https://www.tecgraf.puc-rio.br/iup/en/download_tips.html
Compile from source : https://www.tecgraf.puc-rio.br/iup/en/guide.html#buildlib

**Comment by dariolah** [comment]
Thank you!
I'll update docs

Personally I don't see much appeal into static build of GUI app. E.g. on Linux IUP will depend on on GTK and having GTK statically compiled as well is bigger problem IMHO.

If you distribute application with required DLLs, User can replace them in case of need for fix.

Anyways, thank you for this, I'll include it in docs

**Comment by aldoniel** [comment]
Thanks !
Your point of view is totally valid.
On windows, some people (me) remember the traumatism of missing dll which are a nightmare to find from a trustable source. Some people from python (me...) find it not straightforward to pack and redistribute... So, sometimes, for a small app, I thought that a single file executable might do the trick.

I don't know linux really well, but I suppose you can link again IUP  without GTK.
I have heard of flatpak, snaps, docker and go default static built, which are all again the all philosophy of dynamic linking, but may sometimes lead to dependency troubles.
