### ISSUE TITLE
Unable to install niup via nimble on Windows

### ISSUE THREAD

**Issue by bifunctor** [dariolah/niup#2]
Hello, I am using windows, running on nim v1.0.6 and nimble v0.11.0. When I try to install niup via nimble, this happens:
```shell
C:\Users\Obro>nimble install niup
Downloading https://github.com/dariolah/niup using git
       Tip: 2 messages have been suppressed, use --verbose to show them.
     Error: Could not read package info file in C:\Users\Obro\AppData\Local\T
emp\nimble_394992\githubcom_dariolahniup\niup.nimble;
        ...   Reading as ini file failed with:
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with:
        ...     [Package]
        ... version: """3.28.1"""
        ... author: """Dario Lah"""
        ... description: """IUP FFI bindings"""
        ... license: """MIT"""
        ... backend: """c"""
        ... [Deps]
        ... requires: "nim >= 1.0.4"
        ... C:\Users\Obro\AppData\Local\Temp\nimble_394992\githubcom_dariolah
niup\niup_394992.nims(5, 22) Warning: imported and not used: 'strutils' [UnusedI
mport]
        ... printPkgInfo() failed.

C:\Users\Obro>
```
How could I fix this? Thanks.

**Comment by dariolah** [comment]
I don't have windows environment for testing, so I can't check it right now. Also, for next week or so I'm with limited internet connectivity and time. I'll get back to you

**Comment by dariolah** [comment]
I've tested it with clean Windows 10 install
nimble 0.11
nim 1.06

![niup-install](https://user-images.githubusercontent.com/6512299/75072886-aaa84b00-54f8-11ea-8a5d-b71a32ad460b.png)

No idea what your error means ... try nimble with --debug or --verbose, something to get more details
