### ISSUE TITLE
editor used on screenshots ?

### ISSUE THREAD

**Issue by ffred** [dariolah/niup#3]
Hi, sorry not an issue, just curious.. what is the editor used on the screenshots ?
thanks.

**Comment by dariolah** [comment]
Simple editor is IUP MultiLine control
https://webserver2.tecgraf.puc-rio.br/iup/en/elem/iupmultiline.html

Advanced is Scintilla, bundled with IUP library and exposed through IUP API
https://webserver2.tecgraf.puc-rio.br/iup/en/ctrl/iup_scintilla.html

**Comment by ffred** [comment]
thanks for replying, but I was talking about your IDE/editor on the screenshots.. I didn't recognize it.
I did get it for IUP and Scintilla... sorry, should have made me clearer.. :-)

**Comment by dariolah** [comment]
Editor is Qt Creator

**Comment by ffred** [comment]
oh, ok.. thank you !
