### ISSUE TITLE
Fail to run hello world example

### ISSUE THREAD

**Issue by sucrecacao** [dariolah/niup#4]
# step to reproduce 
install IUP lib as shown in the readme. the install script return:
```
'libiupcd.so' -> '/usr/lib64/libiupcd.so'
'libiupcontrols.so' -> '/usr/lib64/libiupcontrols.so'
'libiupglcontrols.so' -> '/usr/lib64/libiupglcontrols.so'
'libiupgl.so' -> '/usr/lib64/libiupgl.so'
'libiupimglib.so' -> '/usr/lib64/libiupimglib.so'
'libiupim.so' -> '/usr/lib64/libiupim.so'
'libiup_mglplot.so' -> '/usr/lib64/libiup_mglplot.so'
'libiup_plot.so' -> '/usr/lib64/libiup_plot.so'
'libiup_scintilla.so' -> '/usr/lib64/libiup_scintilla.so'
'libiup.so' -> '/usr/lib64/libiup.so'
'libiuptuio.so' -> '/usr/lib64/libiuptuio.so'
'libiupweb.so' -> '/usr/lib64/libiupweb.so'
```

install niup with nimple: 
`nimble install niup`

copy past the quickstart example from the readme into hello.nim

run `nim c -r hello.nim` , which return:
```
/home/joe/nim/hello.nim(2, 8) Error: cannot open file: niupext
```

and if I run `./hello` I get:
```
libiup.so: cannot open shared object file: No such file or directory
could not load: libiup.so
```
# infos
nim version: 1.0.6
nimble version v0.11.0
ubuntu 19.04 Disco Dingo

**Comment by dariolah** [comment]
For first part, IUP lib install, please run:
 `sudo ldconfig -v | grep libiup`

ldconfig will update cache, and display Iup libraries it sees

For second part, I think _niupext_ is not needed in this example. However, if _niup_ is installed correctly, it should not complain. If it comlains then you should check _nimble_ folder, maybe delete _niup_ package and re-install it:
`ls -la ~/.nimble/pkgs/niup*`

Error when running `./hello` is covered in first part. Program tries to load library but it can't find it in path. If everything is ok, `sudo ldconfig` should resolve problem.
