### ISSUE TITLE
can we link iup/cd/... statically?

### ISSUE THREAD

**Issue by retsyo** [dariolah/niup#5]
As the title says, can we link ipu/cd/... into the application so that to release one-file program?

Thanks

**Comment by dariolah** [comment]
Short answer: yes, probably

At the moment, I'm not sure scope of what is possible and exact steps ..

You can statically link IUP but it depends on Gtk/X11 or Win32. I'm not sure that it can be completely statically linked including dependent system libraries.
If you require just IUP and accompanying libs statically linked, it's possible in C.

Statically link it in Nim (NUIP).. It should be same as for C.
NIUP nimble package (niup.nim) will have to be modified not to reference SO/DLLs (dynlib: xxxSONAME ). And when building Nim app, pass list of IUP static libs to be linked.

Look for experiences people had with statically linking in C, it should be same:
https://stackoverflow.com/questions/42660587/iup-windows-sdk-static-link
https://sourceforge.net/p/iup/mailman/message/35202557/
