### ISSUE TITLE
Running examples - Problems with niupext

### ISSUE THREAD

**Issue by super-tomcat** [dariolah/niup#6]
Maybe similar to an earlier problem, i'm on Windows, install niup with:
nimble install niup
Says installed successfully, version 3.30

Try to run any example that uses niupext and get similar to this:

`c:\Users\Neil\Documents\Nim Files\nim-iup-examples-master\example4_3.nim(5, 8) Error: cannot open file: niupext
`

So i look in .Nimble/niup folder and no niupext.nim file in there??

I then download the .zip and extract to the .Nimble/niup folder..... niupext.nim file now in there.

Try to compile again and now i get:

`c:\Users\Neil\Documents\Nim Files\nim-iup-examples-master\example4_3.nim(160, 13) Hint: 'name' is declared but not used [XDeclaredButNotUsed]
c:\Users\Neil\Documents\Nim Files\nim-iup-examples-master\example4_3.nim(160, 8) Hint: 'dir' is declared but not used [XDeclaredButNotUsed]
c:\Users\Neil\Documents\Nim Files\nim-iup-examples-master\example4_3.nim(584, 3) Error: illegal discard proc, did you mean: 
SetCallback(canvas, cstring("ACTION"),
            cast[Icallback](cast[Icallback](canvas_action_cb)))()
`

**Comment by dariolah** [comment]
I have fixed niup package. It will throw warning, but now it installs niupext. Have to change package folder structure .. some other day.

Try uninstall/install of niup package.

In package dir
> pkgs/niup-3.30.1/

there should be niup.nim and niupext.nim

Error you get for illegal discard proc ..
Which version of Nim are you using?

example4_3 compiles fine for me

> nim c --debugInfo --lineDir:on --out:../build-nim-iup-examples-nim-Debug/example4_3 --nimCache:../build-nim-iup-examples-nim-Debug/nimcache --gc:orc example4_3.nim

using
> Nim Compiler Version 1.4.8 [Linux: amd64]

If issue persists, please copy/paste complete compile output

**Comment by super-tomcat** [comment]
Okay, thanks for the reply, most of the examples asking for niupext now compile and run... maybe needed to restart Windows or something after copying niup file into .nimble?

The ones that dont are... 

4.1 = could not import: imImageGetAttribString
4.2 = Error: cannot open file: opengl
4.3 = could not import: cdCanvasActivate
4.4 = could not import: cdCanvasActivate

Anyway ive decided not to use Niup for now as i cannot find a way to put a Button in an iup Matrix control which kind of makes the control a bit useless as a grid :(

**Comment by dariolah** [comment]
IUP is not yet distributed as package but set of libraries. Looks like you are missing IM (iup_im*.dll) and CD libs (cd*.dll).
More info:
https://webserver2.tecgraf.puc-rio.br/iup/en/download_tips.html

There is container IupGridBox -> grid=matrix.

Matrix is 'data' control, not layout container.
Maybe IupMatrixList or IupList can be used like that.

Then there is hard way: IupCells and manual drawing. 

PS I'm cross compiling IUP for Windows with following DLLs:
cdcontextplus.dll
cddirect2d.dll
cd.dll
cdgl.dll
cdim.dll
cdpdf.dll
freetype6.dll
ftgl.dll
iupcd.dll
iupcontrols.dll
iup.dll
iupglcontrols.dll
iupgl.dll
iupim.dll
iupimglib.dll
iup_mglplot.dll
iupole.dll
iup_plot.dll
iup_scintilla.dll
iuptuio.dll
pdflib.dll
zlib1.dll
