### ISSUE TITLE
Error compiling hello sample

### ISSUE THREAD

**Issue by nixfreak** [dariolah/niup#7]
OS: **5.15.7-arch1-1**
ARCH: **x86_64** 
NIM VERS: 1.6.2 **Switched to Nim 1.6.2**

[nixfreak@chaosArch nim-iup-examples]$ `nim c -r --threads:on hello.nim `
Hint: used config file '/home/nixfreak/.choosenim/toolchains/nim-1.6.2/config/nim.cfg' [Conf]                                                                                           
Hint: used config file '/home/nixfreak/.choosenim/toolchains/nim-1.6.2/config/config.nims' [Conf]                                                                                       
.................................................................
/home/nixfreak/nim/gui/nim-iup-examples/hello.nim(8, 7) Error: type mismatch: got <>
but expected one of:
proc Open(argc: var cint; argv: ptr cstringArray): cint

expression: Open()

SOURCE: 

`import niup`

`proc btn_exit_cb(ih:PIhandle):cint {.cdecl.} =`
  `# Exits the main loop`
  `return IUP_CLOSE`

`proc mainProc =`
    `Open()`

  `var`
    `label = Label("Hello world from IUP.")`
    `button = Button("OK")`
    `vbox = Vbox(label, button)`

 ` vbox.alignment = IUP_ACENTER`
  `vbox.gap(10)`
  `vbox.margin(10, 10)`

  `var dlg = Dialog(vbox)`
  `dlg.title = "Hello World"`

  `# callbacks`
  `button.action = btn_exit_cb`

  `ShowXY(dlg, IUP_CENTER, IUP_CENTER)`

  `MainLoop()`
  `  Close()`

`if isMainModule:`
 ` mainProc()`

**Comment by nixfreak** [comment]
I cloned your repo and compiled again and received the **could not load: libiup.so**

So looks like I need to compile iup on arch.

**Comment by nixfreak** [comment]
Closing issue , IUP was not compiled correctly, works now with cloned repo.

**Comment by dariolah** [comment]
Just noticed that releases where not tagged, nimble was installing older version.
When you manually cloned git repo you got OK version, with nimble older which did not match docs.
It should work now with nimble
