### ISSUE TITLE
IUP modern designing

### ISSUE THREAD

**Issue by nixfreak** [dariolah/niup#9]
Is there a way to create a gui with transparency and rounded corners? If so do you have an example?

**Comment by dariolah** [comment]
No example in Nim, but this C example is almost 1-1 with API in "niup/niupc"
https://webserver2.tecgraf.puc-rio.br/iup/examples/C/dialog_ballon.c

Look at Dialog documentation
https://webserver2.tecgraf.puc-rio.br/iup/en/dlg/iupdialog.html

Attributes: BORDER, SHAPEIMAGE, OPACITYIMAGE, OPACITY

For reference on using C-like API there are some examples:
https://github.com/dariolah/nim-iup-examples/tree/master/niupc

based on tutorial in C:
https://webserver2.tecgraf.puc-rio.br/iup/en/tutorial/tutorial.html

**Comment by dariolah** [comment]
Here is Nim example, requires latest niup from master
https://github.com/dariolah/nim-iup-examples/blob/master/niup/dialog_ballon.nim
![ballon](https://user-images.githubusercontent.com/6512299/147103774-554a8f3f-ddda-42ca-8dad-b1cf0983bfce.png)
